### ISSUE TITLE
Rewind draw and fill

### ISSUE THREAD

**Issue by charliecduong** [maxwellito/vivus#116]
Example: http://codepen.io/unpixel/pen/JooWmB

Looking to loop a similar animation. Essentially draw the svg, fill, remove fill, rewind draw in a loop. Do you know if vivus supports this?

**Comment by maxwellito** [comment]
Vivus doesn't support this. 

But you can try that.
PS: I haven't tested it.

```js
new Vivus('mySVG', {}, function (myVivus) {
  if (myVivus.getStatus() === 'end') {
    obj.el.classList.add('finished');
    setTimeout(function(){
      myVivus.play(-1);
      obj.el.classList.add('finished');
    }, 3000);
  }
  else {
    myVivus.play(1);
  }
})
```

```css
/* Style */
#mySVG * {
  fill-opacity: 0;
}

#mySVG.finished * {
  animation: fade 3s ease;
  -webkit-animation: fade 3s ease;
}

@keyframes fade
{
	0% { fill-opacity: 0; }
	30% { fill-opacity: 1; }
	80% { fill-opacity: 1; }
	100% { fill-opacity: 0; }
}
@-webkit-keyframes fade
{
	0% { fill-opacity: 0; }
	30% { fill-opacity: 1; }
	80% { fill-opacity: 1; }
	100% { fill-opacity: 0; }
}
```
