### ISSUE TITLE
How to change stroke color when is on callback?

### ISSUE THREAD

**Issue by joannesalfa** [maxwellito/vivus#170]
I've spent like 2 hours I couldn't figure out how to change color of each stroke path when is on callback. I was using css animation to make color transition in the end. Using Class or ID in CSS or Javascript selector are useless.

**Comment by maxwellito** [comment]
Do you have an example?

The following should work.

```html
<svg id="mySVG">
  <line class="arc_1"/>
  <line class="arc_2"/>
  <line class="arc_3"/>
</svg>
```

```css
.arc_1 {stroke: #555;}
.arc_2 {stroke: #666;}
.arc_3 {stroke: #777;}

.rainbow * {transition: stroke 1s;}
.rainbow .arc_1 {stroke: red;}
.rainbow .arc_2 {stroke: green;}
.rainbow .arc_3 {stroke: blue;}
```

```js
new Vivus('mySVG', {}, function (obj) {
  obj.el.classList.add('rainbow');
});
```
